# fly.toml app configuration file generated for prereview-matchmaking-experiment on 2026-03-05T11:23:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prereview-matchmaking-experiment'
primary_region = 'lhr'

[build]

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "1m"
  interval = "30s"
  method = "GET"
  timeout = "1s"
  path = "/"

[[http_service.machine_checks]]
  image = "curlimages/curl"
  entrypoint = ["/bin/sh", "-c"]
  command = ["curl --fail --retry-delay 5 --retry 1000 --retry-connrefused http://[$FLY_TEST_MACHINE_IP]:8080"]
  kill_signal = "SIGKILL"
  kill_timeout = "5m"

[[vm]]
  memory = '2gb'
  cpus = 1
  cpu_kind = "performance"
